### ISSUE TITLE
Cant click on buttons when loading.

### ISSUE THREAD

**Issue by venehanno** [Lapikud/Viido#1]
Cant click on mopidy, vnc or kodi when it's warming up the projector. Just disable the 3 projector buttons instead of the overlay.

**Comment by siinus** [comment]
projektor service issue. Projector state change is waiting for /projektor/status response. Who the f* speaks python, could rewrite projektor code to drop VGA/HDMI switch and skip projectors status during startup. We only have 2 states now (HDMI and OFF). 40-ish seconds wait time isn't the point anymore.

**Comment by siinus** [comment]
põmst projektor võiks kohe vastata kui "ON" command antud :D
tehke ära. Ei viitsi Engrishi purssida.
Sander lubas ära teha :)

**Comment by artizirk** [comment]
Done
